Update run-DNSrank
Enabled autoupdates

diff --git a/run-DNSrank b/run-DNSrank
--- a/run-DNSrank
+++ b/run-DNSrank
@@ -8,7 +8,7 @@
 #  | |__| | |\  |____) | | | (_| | | | |   <   #
 #  |_____/|_| \_|_____/|_|  \__,_|_| |_|_|\_\  #
 # 				               #  
-#  DNSrank version 1.1/20.Jan.2022	       #
+#  DNSrank version 1.2/20.Jan.2022	       #
 #  License: GPL-3.0			       #
 #  Github: https://github.com/Deepcuts/DNSrank #
 #  razvan.constantin@gmail.com	       	       #	
@@ -51,6 +51,10 @@ pingtime=4
 bestqt=10
 worstqt=100
 
+# Enable checking for update. If enabled (true), the script will pull the latest version from github, overwriting any local modifications. If false, no update check or changes will be made.
+# Default true
+check4update=true
+
 #------------------------------------------------------------------------------------------------------------------------
 #		Edit below only if you know what you are doing and you want to modify the script 			#
 #------------------------------------------------------------------------------------------------------------------------
@@ -62,12 +66,26 @@ worstqt=100
 
 
 
-
-
-
-
-
-
+# Check for update and if enabled, pull the latest version. 
+if [ $check4update = "true" ]; then
+    printf "Checking for update...\n"
+    [ $(git rev-parse HEAD) = $(git ls-remote $(git rev-parse --abbrev-ref @{u} | \
+    sed 's/\// /g') | cut -f1) ] && needupdate=0 || needupdate=1
+    if [ $needupdate = 1 ]; then
+	printf "Update found. Applying...\n"
+	git reset --hard HEAD
+	git pull
+    fi
+    if [ $needupdate = 0 ]; then
+	printf "No update found. \n"
+    fi
+fi
+if [ $check4update = "false" ]; then
+    :
+fi
+if [ $check4update != "true" ] && [ $check4update != "false" ]; then
+    printf "Set check4update variable to true or false to enable or disable checking for updates \n"
+fi
 
 # Set script git home
 githome="https://github.com/Deepcuts/DNSrank"
@@ -90,28 +108,28 @@ fi
 
 # Checking if required commands are available.
 if ! [ -x "$(command -v bc)" ]; then
-  printf "${RED}Error: bc is not installed. Script halted! ${normal} \n"
-  exit 1
+	printf "${RED}Error: bc is not installed. Script halted! ${normal} \n"
+ 	exit 1
 fi
 if ! [ -x "$(command -v dig)" ]; then
-  printf "${RED}Error: dig is not installed. Script halted! ${normal} \n"
-  exit 1
+	printf "${RED}Error: dig is not installed. Script halted! ${normal} \n"
+	exit 1
 fi
 if ! [ -x "$(command -v traceroute)" ]; then
-  printf "${RED}Error: traceroute is not installed. Script halted! ${normal} \n"
-  exit 1
+	printf "${RED}Error: traceroute is not installed. Script halted! ${normal} \n"
+  	exit 1
 fi
 if ! [ -x "$(command -v ping)" ]; then
-  printf "${RED}Error: ping is not installed. Script halted! ${normal} \n"
-  exit 1
+  	printf "${RED}Error: ping is not installed. Script halted! ${normal} \n"
+  	exit 1
 fi
 if ! [ -x "$(command -v curl)" ]; then
-  printf "${RED}Error: curl is not installed. Script halted! ${normal} \n"
-  exit 1
+  	printf "${RED}Error: curl is not installed. Script halted! ${normal} \n"
+  	exit 1
 fi
 if ! [ -x "$(command -v getent)" ]; then
-  printf "${RED}Error: getent is not installed. Script halted! ${normal} \n"
-  exit 1
+  	printf "${RED}Error: getent is not installed. Script halted! ${normal} \n"
+  	exit 1
 fi
 
 # Zeroing required variables just in case.
@@ -134,7 +152,7 @@ Servers=$(cat "$ServersFile")
 
 # Counting final number of domains to test.
 for d1 in $Domains; do
-    totaldomains=$((totaldomains + 1))
+	totaldomains=$((totaldomains + 1))
 done
 
 # Counting number of DNS servers to use.
@@ -168,7 +186,7 @@ if [ $totaldomains -eq 1 ]; then
     gdomains="domain"
 fi
 if [ $totaldomains -ge 2 ]; then
-    gdomains="domains"
+	gdomains="domains"
 fi
 
 # Display some test info, parameters and legend.
@@ -217,36 +235,36 @@ for s1 in $Servers; do
     printf "\n%22s%s:" $sname
     # Test each DNS server if value is an IP and skip it if it is not.
     if [[ $sip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-	:
+		:
     else
-	printf "  ${RED}Server is not an IP. Skipping!${normal}"
-	badservers=$((badservers + 1))
-	continue
+		printf "  ${RED}Server is not an IP. Skipping!${normal}"
+		badservers=$((badservers + 1))
+		continue
     fi
     # Test each DNS server and skip it if packet loss is 100%.
     pktloss=`ping -W 2 -i 1 -n -c $pingtime $sip | grep -oP '\d+(?=% packet loss)'`
     if [ "$pktloss" = "100" ]; then 
-	printf "  ${RED}Server not responding to icmp requests. Skipping!${normal}"
-	badservers=$((badservers + 1))
-	continue 
+		printf "  ${RED}Server not responding to icmp requests. Skipping!${normal}"
+		badservers=$((badservers + 1))
+		continue 
     fi
     # Test each DNS server and skip it if unable to query some hopefully always online domains.
     testdns=`dig -p $sport +tries=1 +retry=1 +time=1 @$sip +short google.com apple.com microsoft.com`
     if [ $? -eq 0 ]; then
-	:
+		:
     else
-	printf "  ${RED}Server not responding to DNS queries. Skipping!${normal}"
-	badservers=$((badservers + 1))
+		printf "  ${RED}Server not responding to DNS queries. Skipping!${normal}"
+		badservers=$((badservers + 1))
         continue
     fi
     # Test each DNS server and skip it if recursion is not available.
     testdns1=`dig -p $sport +tries=1 +retry=1 +time=1 @$sip google.com apple.com microsoft.com | grep "WARNING: recursion requested but not available" `
     if [ $? -eq 0 ]; then
-	printf "  ${RED}Server reporting that recursion is not available. Skipping!${normal}"
-	badservers=$((badservers + 1))
+		printf "  ${RED}Server reporting that recursion is not available. Skipping!${normal}"
+		badservers=$((badservers + 1))
         continue
     else
-	:
+		:
     fi
     # Find max hops to each DNS server with traceroute.
     troute=`traceroute -n -I "$sip" 2>/dev/null | tail -1 | awk '{print $1}'`
@@ -258,12 +276,12 @@ for s1 in $Servers; do
     # Loop all domains.
     for d1 in $Domains; do
 	# Query each server and look for Query time value in reponse.
-        ttime=`dig -p $sport +tries=1 +retry=1 +time=$querytime +stats @$sip $d1 | grep "Query time:" | cut -d : -f 2- | cut -d " " -f 2`
+    	ttime=`dig -p $sport +tries=1 +retry=1 +time=$querytime +stats @$sip $d1 | grep "Query time:" | cut -d : -f 2- | cut -d " " -f 2`
         if [ -z "$ttime" ]; then
-	    ttime=1000
+	    	ttime=1000
         elif [ "x$ttime" = "x0" ]; then
-	    ttime=1
-	fi
+	    	ttime=1
+		fi
         ftime=$((ftime + ttime))
     done
     # Do some math for each DNS server final query average time.
@@ -271,17 +289,17 @@ for s1 in $Servers; do
     # Print statistics for each DNS server
     # Mark servers with a query time lower than $bestqt with a different color.
     if (( $(echo "$avg < $bestqt" |bc -l) )); then
-	printf "%8s%s" ${GREEN} $avg " ms (average) | Distance to server: $troute hops | icmp rtt: $rttavg ms (average) | packet loss: $pktloss% | version: $dnsversion ${normal}"
-	continue
+		printf "%8s%s" ${GREEN} $avg " ms (average) | Distance to server: $troute hops | icmp rtt: $rttavg ms (average) | packet loss: $pktloss% | version: $dnsversion ${normal}"
+		continue
     fi
     # Mark servers with a query time higher than $worstqt with a different color.
     if (( $(echo "$avg > $worstqt" |bc -l) )); then
-	printf "%6s%s" ${RED} $avg " ms (average) | Distance to server: $troute hops | icmp rtt: $rttavg ms (average) | packet loss: $pktloss% | version: $dnsversion ${normal}"
-	continue
+		printf "%6s%s" ${RED} $avg " ms (average) | Distance to server: $troute hops | icmp rtt: $rttavg ms (average) | packet loss: $pktloss% | version: $dnsversion ${normal}"
+		continue
     fi
     # Mark servers with a query time between $bestqt and $worstqt with a different color.
     if (( $(echo "$avg > $bestqt" |bc -l) && $(echo "$avg < $worstqt" |bc -l ))); then
-	printf "%7s%s" ${YELLOW} $avg " ms (average) | Distance to server: $troute hops | icmp rtt: $rttavg ms (average) | packet loss: $pktloss% | version: $dnsversion ${normal}"
+		printf "%7s%s" ${YELLOW} $avg " ms (average) | Distance to server: $troute hops | icmp rtt: $rttavg ms (average) | packet loss: $pktloss% | version: $dnsversion ${normal}"
     fi
 done
 # Main loop done.
@@ -290,17 +308,17 @@ if [ $badservers -ge 1 ]; then
     testedservers=$((totalservers - badservers))
     # Some grammar fixes.
     if [ $testedservers -eq 1 ]; then
-	g1servers="server"
-	g1has="has"
+		g1servers="server"
+		g1has="has"
     fi
     if [ $testedservers -ge 2 ]; then
-	g1servers="servers"
-	g1has="have"
+		g1servers="servers"
+		g1has="have"
     fi
     # Notify that not even one server was tested.
     if [ $testedservers -eq 0 ]; then
-	printf "\n%s\n" "Not even one server responded to DNS queries. Check your network connection or the configured DNS servers. \n"
-	exit 1
+		printf "\n%s\n" "Not even one server responded to DNS queries. Check your network connection or the configured DNS servers. \n"
+		exit 1
     fi
     # Notiy that some servers were not reachable while others were.
     printf "\n%s" "$badservers out of $totalservers $gservers failed to respond to DNS queries. $testedservers $g1servers responded to queries and $g1has been tested. \n"
